// Real-world process names and window titles (Windows exe names, macOS app names, browser tabs)
// with the category a person would expect. Used to measure and guard the classifier.
import type { Category } from "../categories";

export interface CorpusCase {
  process: string;
  title: string;
  expected: Category;
  /** Metadata the agent reads from the app itself (macOS Info.plist, Windows version info / path). */
  hint?: { kind?: string; description?: string; publisher?: string; path?: string };
  note?: string;
}

const c = (process: string, title: string, expected: Category, hint?: CorpusCase["hint"], note?: string): CorpusCase => ({ process, title, expected, hint, note });

export const CORPUS: CorpusCase[] = [
  // ---- Browsers: the site decides -------------------------------------------------------------
  c("chrome", "Pull requests · TempestShaw/Dopamine · GitHub - Google Chrome", "work"),
  c("chrome", "Inbox (3) - me@gmail.com - Gmail - Google Chrome", "work"),
  c("chrome", "Untitled document - Google Docs - Google Chrome", "work"),
  c("chrome", "Q3 plan - Google Sheets - Google Chrome", "work"),
  c("chrome", "ChatGPT - Google Chrome", "work"),
  c("chrome", "localhost:3000 - Google Chrome", "work"),
  c("chrome", "javascript - How to debounce in React? - Stack Overflow - Google Chrome", "work"),
  c("chrome", "Array.prototype.map() - JavaScript | MDN - Google Chrome", "work"),
  c("chrome", "YouTube - Google Chrome", "entertainment"),
  c("chrome", "(12) lofi hip hop radio - beats to relax/study to - YouTube - Google Chrome", "entertainment"),
  c("chrome", "Netflix - Google Chrome", "entertainment"),
  c("chrome", "Twitch - Google Chrome", "entertainment"),
  c("chrome", "【4K】城市漫步 - 哔哩哔哩 bilibili - Google Chrome", "entertainment"),
  // Learning on video sites counts as study; the topic words win over the platform.
  c("Arc", "教你网络基础", "study"),
  c("Arc", "Python 零基础入门教程_哔哩哔哩_bilibili", "study"),
  c("chrome", "CS50 2024 - Lecture 3 - Algorithms - YouTube - Google Chrome", "study"),
  c("chrome", "React Tutorial for Beginners - YouTube - Google Chrome", "study"),
  c("Arc", "特厨探店｜最擅长做鲍鱼的餐厅？！阿一鲍鱼！_哔哩哔哩_bilibili", "entertainment"),
  c("Arc", "冷知识:羂索和芥见下下是会中文的_哔哩哔哩_bilibili", "entertainment"),
  c("chrome", "Home / X - Google Chrome", "social"),
  c("chrome", "(3) Feed | LinkedIn - Google Chrome", "social"),
  c("chrome", "r/cmu - Reddit - Google Chrome", "social"),
  c("chrome", "Instagram - Google Chrome", "social"),
  c("chrome", "小红书 - 你的生活指南 - Google Chrome", "social"),
  c("chrome", "如何评价……? - 知乎 - Google Chrome", "social"),
  c("chrome", "Dashboard - Canvas - Google Chrome", "study"),
  c("chrome", "15-213 Homework 3 | Gradescope - Google Chrome", "study"),
  c("chrome", "Attention Is All You Need - arXiv - Google Chrome", "study"),
  c("chrome", "Google Scholar - Google Chrome", "study"),
  c("chrome", "Two Sum - LeetCode - Google Chrome", "study"),
  c("chrome", "Photosynthesis - Wikipedia - Google Chrome", "study"),
  c("chrome", "Machine Learning | Coursera - Google Chrome", "study"),
  c("chrome", "中国知网 - Google Chrome", "study"),
  c("chrome", "New Tab - Google Chrome", "other"),
  c("chrome", "Amazon.com: Wireless Mouse - Google Chrome", "other"),
  c("chrome", "Free Barcode Generator - Google Chrome", "other", undefined, "'code' must not match inside 'Barcode'"),
  c("msedge", "Docs - Personal - Microsoft\u200b Edge", "other"),
  c("msedge", "Outlook - Microsoft\u200b Edge", "work"),
  c("firefox", "Spotify – Web Player - Mozilla Firefox", "entertainment"),
  c("Safari", "WhatsApp", "social"),
  c("Safari", "Apple (United States)", "other"),
  c("Arc", "Linear - Issues", "work"),
  c("Brave Browser", "Discord | #general", "social"),
  c("Google Chrome", "Figma", "work"),
  c("Microsoft Edge", "Blackboard Learn", "study"),

  // ---- Windows executables -------------------------------------------------------------------
  c("Code", "analytics.ts - Dopamine - Visual Studio Code", "work"),
  c("idea64", "Dopamine – Main.java", "work"),
  c("pycharm64", "train.py", "work"),
  c("devenv", "DopamineWin - Microsoft Visual Studio", "work"),
  c("WindowsTerminal", "Windows PowerShell", "work"),
  c("cmd", "Command Prompt", "work"),
  c("WINWORD", "Essay draft.docx - Word", "work"),
  c("EXCEL", "Budget.xlsx - Excel", "work"),
  c("POWERPNT", "Pitch.pptx - PowerPoint", "work"),
  c("ms-teams", "Chat | Microsoft Teams", "work"),
  c("Zoom", "Zoom Meeting", "work"),
  c("slack", "general (Channel) - Acme - Slack", "work"),
  c("Postman", "My Workspace", "work"),
  c("WXWork", "企业微信", "work"),
  c("DingTalk", "钉钉", "work"),
  c("Feishu", "飞书", "work"),
  c("Discord", "#general | Study Group - Discord", "social"),
  c("WeChat", "微信", "social"),
  c("QQ", "QQ", "social"),
  c("Telegram", "Telegram", "social"),
  c("Spotify", "Spotify Premium", "entertainment"),
  c("cloudmusic", "网易云音乐", "entertainment"),
  c("steamwebhelper", "Steam", "entertainment"),
  c("EpicGamesLauncher", "Epic Games Launcher", "entertainment"),
  c("LeagueClientUx", "League of Legends", "entertainment"),
  c("VALORANT-Win64-Shipping", "VALORANT  ", "entertainment"),
  c("GenshinImpact", "原神", "entertainment"),
  c("cs2", "Counter-Strike 2", "entertainment"),
  c("javaw", "Minecraft 1.20.1", "entertainment", undefined, "generic runtime; the title names the game"),
  c("vlc", "movie.mkv - VLC media player", "entertainment"),
  c("PotPlayerMini64", "episode01.mp4 - PotPlayer", "entertainment"),
  c("AcroRd32", "Lecture 7 - Scheduling.pdf - Adobe Acrobat Reader", "study"),
  c("SumatraPDF", "paper.pdf - SumatraPDF", "study"),
  c("zotero", "My Library - Zotero", "study"),
  c("Obsidian", "Notes - Obsidian", "study"),
  c("ONENOTE", "Biology - OneNote", "study"),
  c("anki", "Anki - User 1", "study"),
  c("explorer", "Downloads", "other"),
  c("explorer", "C:\\Users\\me\\Code", "other", undefined, "a folder named Code is still File Explorer"),
  c("Taskmgr", "Task Manager", "other"),
  c("SystemSettings", "Settings", "other"),
  c("notepad", "todo.txt - Notepad", "other"),
  c("notepad++", "main.cpp - Notepad++", "work", undefined, "not plain Notepad"),
  c("Photoshop", "poster.psd @ 50%", "work"),
  c("blender", "scene.blend - Blender", "work"),

  // ---- macOS apps ----------------------------------------------------------------------------
  c("Xcode", "DopamineMac — Tracker.swift", "work"),
  c("Cursor", "page.tsx — dopamine", "work"),
  c("iTerm2", "zsh", "work"),
  c("Warp", "~/code", "work"),
  c("Terminal", "bash — 80×24", "work"),
  c("Mail", "Inbox", "work"),
  c("Calendar", "Calendar", "work"),
  c("Keynote", "Talk.key", "work"),
  c("Notion", "Sprint planning", "study"),
  c("Preview", "Lecture 3.pdf", "study"),
  c("Books", "Deep Work", "study"),
  c("Messages", "Mom", "social"),
  c("FaceTime", "FaceTime", "social"),
  c("Music", "Music", "entertainment"),
  c("TV", "Severance", "entertainment"),
  c("IINA", "movie.mkv", "entertainment"),
  c("Finder", "Documents", "other"),
  c("System Settings", "Wi-Fi", "other"),
  c("1Password", "1Password", "other"),

  // ---- Apps nobody wrote a rule for: the agent's metadata has to carry them ------------------
  c("Balatro", "Balatro", "entertainment", { kind: "public.app-category.card-games" }, "macOS game with only its category in Info.plist"),
  c("Hollow Knight", "Hollow Knight", "entertainment", { path: "D:\\SteamLibrary\\steamapps\\common\\Hollow Knight\\hollow_knight.exe" }),
  c("StarRail", "崩坏：星穹铁道", "entertainment", { publisher: "COGNOSPHERE PTE. LTD.", path: "C:\\Program Files\\HoYoPlay\\games\\Star Rail Games\\StarRail.exe" }),
  c("Craft", "Weekly review", "work", { kind: "public.app-category.productivity" }),
  c("Kaleidoscope", "diff", "work", { kind: "public.app-category.developer-tools" }),
  c("Pixelmator Pro", "photo.pxd", "work", { kind: "public.app-category.graphics-design" }),
  c("Flashcards Pro", "Deck", "study", { kind: "public.app-category.education" }),
  c("Ivory", "Home", "social", { kind: "public.app-category.social-networking" }),
  c("Reeder", "All unread", "other", { kind: "public.app-category.news" }),
  c("obsidian-alt", "Vault", "study", { description: "Obsidian" }, "renamed exe; version info still says Obsidian"),
  c("unknowntool", "Main window", "work", { description: "JetBrains Toolbox", publisher: "JetBrains s.r.o." }),
  c("SomeGame", "SomeGame", "entertainment", { publisher: "Valve Corporation" }),
];
