// Held-out cases: written after the rules, never used to tune them. The score on these is the
// honest estimate of how the classifier does on apps and sites it hasn't been shown.
import type { CorpusCase } from "./categorize-corpus";

const c = (process: string, title: string, expected: CorpusCase["expected"], hint?: CorpusCase["hint"]): CorpusCase => ({ process, title, expected, hint });

export const HOLDOUT: CorpusCase[] = [
  c("chrome", "Merge requests · group/project · GitLab - Google Chrome", "work"),
  c("chrome", "Sign in - Google Accounts - Google Chrome", "other"),
  c("chrome", "Weather in Pittsburgh - Google Chrome", "other"),
  c("chrome", "Hacker News - Google Chrome", "social"),
  c("chrome", "Duolingo - The world's best way to learn a language - Google Chrome", "study"),
  c("chrome", "Khan Academy | Free Online Courses - Google Chrome", "study"),
  c("chrome", "Prime Video: The Boys - Google Chrome", "entertainment"),
  c("chrome", "Crunchyroll - Watch Popular Anime - Google Chrome", "entertainment"),
  c("chrome", "Messenger | Facebook - Google Chrome", "social"),
  c("chrome", "Jira - Board - Google Chrome", "work"),
  c("chrome", "Vercel – Dashboard - Google Chrome", "work"),
  c("chrome", "Hugging Face – The AI community - Google Chrome", "work"),
  c("chrome", "Overleaf, Online LaTeX Editor - Google Chrome", "study"),
  c("chrome", "抖音-记录美好生活 - Google Chrome", "entertainment"),
  c("chrome", "豆瓣电影 - Google Chrome", "social"),
  c("chrome", "淘宝网 - 淘！我喜欢 - Google Chrome", "other"),
  c("msedge", "Microsoft Copilot - Microsoft\u200b Edge", "work"),
  c("firefox", "Pinterest - Mozilla Firefox", "social"),
  c("Safari", "Apple Music - Web Player", "entertainment"),
  c("Safari", "Wolfram|Alpha: Computational Intelligence", "study"),
  c("Code - Insiders", "index.ts - app", "work"),
  c("GoogleDriveFS", "Google Drive", "other"),
  c("Spark Desktop", "Inbox", "work"),
  c("Notion Calendar", "Week 39", "work"),
  c("Microsoft Teams (work or school)", "Calendar", "work"),
  c("Skype", "Skype", "social"),
  c("KakaoTalk", "KakaoTalk", "social"),
  c("Signal", "Signal", "social"),
  c("Overwatch", "Overwatch", "entertainment"),
  c("RobloxPlayerBeta", "Roblox", "entertainment"),
  c("Minecraft Launcher", "Minecraft Launcher", "entertainment"),
  c("osu!", "osu!", "entertainment", { path: "C:\\Users\\me\\AppData\\Local\\osu!\\osu!.exe", publisher: "ppy Pty Ltd" }),
  c("Stardew Valley", "Stardew Valley", "entertainment", { kind: "public.app-category.simulation-games" }),
  c("Cyberpunk2077", "Cyberpunk 2077", "entertainment", { path: "D:\\GOG Galaxy\\Games\\Cyberpunk 2077\\bin\\x64\\Cyberpunk2077.exe" }),
  c("GoodNotes", "Organic Chemistry", "study"),
  c("Mathematica", "Untitled-1", "study"),
  c("Quizlet", "Flashcards", "study", { kind: "public.app-category.education" }),
  c("TablePlus", "prod — users", "work"),
  c("OrbStack", "Containers", "work", { kind: "public.app-category.developer-tools" }),
  c("Proxyman", "Sessions", "work", { kind: "public.app-category.developer-tools" }),
  c("CleanMyMac", "Smart Care", "other", { kind: "public.app-category.utilities" }),
  c("Rectangle", "Rectangle", "other", { kind: "public.app-category.productivity" }),
  c("Photos", "Library", "other"),
  c("QuickTime Player", "screen recording.mov", "entertainment"),
  c("OBS", "OBS 30.0 - Profile: Untitled", "work"),
  c("WeChatAppEx", "小程序", "social"),
  c("Tencent Meeting", "腾讯会议", "work"),
  c("Lark", "Messenger", "work"),
];
