// Generated from DopamineWeb/src/lib/category-rules.json by `bun run sync-rules`. Do not edit.

let categoryRulesJSON = #"""
{
  "_comment": "Shared by the dashboard (categories.ts) and the macOS agent (CategoryRules.swift, generated by `bun run sync-rules`). Keywords are matched case-insensitively on word boundaries; non-Latin keywords match anywhere. Earlier rules win.",
  "browsers": ["chrome", "google chrome", "chromium", "msedge", "microsoft edge", "firefox", "safari", "arc", "brave", "brave browser", "opera", "vivaldi", "orion", "zen", "zen browser", "qqbrowser", "sogouexplorer", "360se", "360chrome", "duckduckgo", "whale"],
  "sites": [
    ["entertainment", ["youtube", "netflix", "twitch", "hulu", "disney+", "prime video", "hbo", "crunchyroll", "spotify", "apple music", "soundcloud", "bilibili", "哔哩哔哩", "抖音", "douyin", "tiktok", "快手", "iqiyi", "爱奇艺", "youku", "优酷", "腾讯视频", "芒果tv", "网易云音乐", "qq音乐", "steam", "epic games", "itch.io", "roblox", "minecraft", "9gag", "imgur", "espn", "letterboxd", "imdb"]],
    ["social", ["facebook", "instagram", "twitter", "/ x", "on x", "x.com", "reddit", "linkedin", "threads", "mastodon", "bluesky", "discord", "whatsapp", "telegram", "messenger", "wechat", "微信", "微博", "weibo", "小红书", "xiaohongshu", "rednote", "知乎", "zhihu", "豆瓣", "douban", "贴吧", "tieba", "snapchat", "pinterest", "tumblr", "quora", "hacker news", "v2ex"]],
    ["study", ["canvas", "blackboard", "moodle", "gradescope", "piazza", "ed discussion", "coursera", "udemy", "edx", "khan academy", "brilliant", "duolingo", "quizlet", "chegg", "wikipedia", "维基百科", "百度百科", "google scholar", "scholar", "arxiv", "researchgate", "jstor", "pubmed", "sciencedirect", "springer", "ieee xplore", "acm digital library", "overleaf", "wolfram", "wolframalpha", "desmos", "leetcode", "力扣", "geeksforgeeks", "khanacademy", "opencourseware", "中国大学mooc", "学堂在线", "知网", "cnki", "lecture", "syllabus", "homework", "assignment", ".pdf"]],
    ["work", ["github", "gitlab", "bitbucket", "stack overflow", "stackoverflow", "mdn", "jira", "confluence", "linear", "notion calendar", "trello", "asana", "clickup", "monday.com", "miro", "figma", "canva", "google docs", "google sheets", "google slides", "google drive", "gmail", "outlook", "office 365", "microsoft 365", "sharepoint", "onedrive", "google meet", "zoom", "slack", "microsoft teams", "calendar", "chatgpt", "claude", "gemini", "copilot", "perplexity", "vercel", "netlify", "aws", "azure", "google cloud", "firebase", "supabase", "cloudflare", "npm", "pypi", "docker hub", "hugging face", "kaggle", "localhost", "127.0.0.1", "飞书", "钉钉", "语雀", "腾讯文档", "石墨文档"]]
  ],
  "apps": [
    ["other", ["finder", "explorer", "file explorer", "system settings", "system preferences", "systemsettings", "settings", "taskmgr", "task manager", "activity monitor", "control panel", "1password", "bitwarden", "keychain access", "raycast", "alfred", "spotlight", "searchhost", "searchapp", "shellexperiencehost", "lockapp", "loginwindow", "textedit", "calculator", "screenshot", "snipping tool", "app store", "microsoft store"]],
    ["work", ["code", "vs code", "visual studio", "devenv", "cursor", "zed", "xcode", "android studio", "studio 64", "idea", "intellij", "webstorm", "pycharm", "goland", "rider", "clion", "rubymine", "phpstorm", "datagrip", "fleet", "sublime text", "sublime", "vim", "nvim", "neovim", "emacs", "notepad++", "terminal", "windows terminal", "iterm", "iterm 2", "warp", "alacritty", "kitty", "wezterm", "ghostty", "hyper", "powershell", "pwsh", "cmd", "conhost", "wsl", "github desktop", "sourcetree", "fork", "tower", "gitkraken", "docker", "docker desktop", "postman", "insomnia", "tableplus", "dbeaver", "sequel ace", "pgadmin", "mongodb compass", "slack", "teams", "ms teams", "zoom", "webex", "lark", "feishu", "飞书", "dingtalk", "钉钉", "wxwork", "企业微信", "outlook", "mail", "thunderbird", "spark", "airmail", "calendar", "fantastical", "word", "winword", "excel", "powerpnt", "powerpoint", "keynote", "pages", "numbers", "wps", "figma", "sketch", "photoshop", "illustrator", "indesign", "after effects", "afterfx", "premiere", "adobe premiere pro", "lightroom", "affinity", "pixelmator", "blender", "unity", "unreal editor", "godot", "final cut", "final cut pro", "logic pro", "davinci resolve", "resolve", "linear", "jira", "things", "todoist", "omnifocus", "reminders", "trello", "asana", "clickup", "chatgpt", "claude", "copilot", "matlab", "rstudio", "jupyter", "anaconda", "spyder", "tableau", "power bi", "jetbrains", "toolbox", "obs", "obs 64", "obs studio", "tencent meeting", "腾讯会议", "voov", "wemeet"]],
    ["study", ["notion", "obsidian", "onenote", "evernote", "bear", "logseq", "roam", "anki", "kindle", "books", "ibooks", "preview", "acrobat", "acrord", "acro rd", "adobe acrobat", "sumatrapdf", "sumatra pdf", "foxit", "skim", "pdf expert", "zotero", "mendeley", "endnote", "readwise", "notability", "goodnotes", "marginnote", "mathematica", "wolfram", "geogebra", "duolingo"]],
    ["social", ["discord", "wechat", "wechatappex", "weixin", "微信", "qq", "tim", "telegram", "whatsapp", "signal", "messenger", "messages", "facetime", "line", "kakaotalk", "skype"]],
    ["entertainment", ["spotify", "music", "apple music", "itunes", "quicktime player", "quicktime", "tv", "apple tv", "podcasts", "vlc", "iina", "infuse", "potplayer", "pot player mini", "mpv", "netflix", "steam", "steamwebhelper", "steam web helper", "epic games", "epic games launcher", "battle.net", "league of legends", "league client", "league client ux", "riot client", "valorant", "minecraft", "roblox", "genshin", "genshin impact", "原神", "star rail", "崩坏", "zenless", "绝区零", "honkai", "cs2", "counter-strike", "csgo", "dota 2", "dota2", "overwatch", "fortnite", "apex", "pubg", "tslgame", "gta", "elden ring", "eldenring", "cloudmusic", "网易云音乐", "qqmusic", "qq音乐", "kugou", "酷狗", "bilibili", "哔哩哔哩", "douyin", "抖音", "tiktok", "iqiyi", "爱奇艺", "youku", "qqlive", "腾讯视频", "twitch"]]
  ],
  "platformKinds": {
    "public.app-category.developer-tools": "work",
    "public.app-category.productivity": "work",
    "public.app-category.business": "work",
    "public.app-category.graphics-design": "work",
    "public.app-category.finance": "work",
    "public.app-category.video": "entertainment",
    "public.app-category.music": "entertainment",
    "public.app-category.entertainment": "entertainment",
    "public.app-category.sports": "entertainment",
    "public.app-category.games": "entertainment",
    "public.app-category.education": "study",
    "public.app-category.reference": "study",
    "public.app-category.social-networking": "social",
    "public.app-category.news": "other",
    "public.app-category.utilities": "other",
    "public.app-category.lifestyle": "other",
    "public.app-category.travel": "other",
    "public.app-category.weather": "other"
  },
  "gamePaths": ["steamapps", "epic games", "riot games", "xboxgames", "gog galaxy", "battle.net", "ubisoft game launcher", "hoyoplay", "mihoyo", "genshin impact game", "wegame", "netease games"],
  "gamePublishers": ["valve", "riot games", "mihoyo", "hoyoverse", "cognosphere", "blizzard", "epic games", "ubisoft", "electronic arts", "rockstar games", "cd projekt", "mojang", "bandai namco", "square enix", "capcom", "sega", "krafton", "netease games", "team cherry", "supergiant", "localthunk"]
}
"""#
